Repository securefederatedai/openfl, pull requests merged in 2021-11, with the labels that each got.

#206 General split to ShardDescriptor and ShardDataset
  openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy/kvasir_shard_descriptor.py
  openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy/kvasir_shard_descriptor_with_data_splitter.py
  openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/workspace/PyTorch_Kvasir_UNet.ipynb
  openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/envoy/envoy_config_one.yaml
  openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/envoy/envoy_config_two.yaml
  openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/envoy/market_shard_descriptor.py
  openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/PyTorch_Market_Re-ID.ipynb
  openfl-tutorials/interactive_api/PyTorch_TinyImageNet/director/director_config.yaml
  openfl-tutorials/interactive_api/PyTorch_TinyImageNet/envoy/base.py
  openfl-tutorials/interactive_api/PyTorch_TinyImageNet/envoy/tinyimagenet_shard_descriptor.py
  openfl-tutorials/interactive_api/PyTorch_TinyImageNet/workspace/pytorch_tinyimagenet.ipynb
  openfl-tutorials/interactive_api/Tensorflow_MNIST/envoy/mnist_shard_descriptor.py
  openfl-tutorials/interactive_api/Tensorflow_MNIST/workspace/Tensorflow_MNIST.ipynb
  openfl/interface/interactive_api/shard_descriptor.py
  openfl/transport/grpc/director_client.py
  tests/github/interactive_api_director/experiments/pytorch_kvasir_unet/envoy/envoy_config.yaml
  tests/github/interactive_api_director/experiments/pytorch_kvasir_unet/envoy/kvasir_shard_descriptor.py
  tests/github/interactive_api_director/experiments/pytorch_kvasir_unet/experiment.py
  tests/openfl/api_layer/test_federation.py
  tests/openfl/communication/test_envoys_client.py
Labels: enhancement

#174 Get experiments from director
  openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy/kvasir_shard_descriptor.py
  openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy/sd_requirements.txt
  openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/workspace/PyTorch_Kvasir_UNet.ipynb
  openfl/component/director/director.py
  openfl/component/director/experiment.py
  openfl/component/envoy/envoy.py
  openfl/plugins/processing_units_monitor/cuda_device_monitor.py
  openfl/plugins/processing_units_monitor/pynvml_monitor.py
  openfl/protocols/director.proto
  openfl/protocols/director_pb2.py
  openfl/protocols/director_pb2_grpc.py
  openfl/transport/grpc/director_client.py
  openfl/transport/grpc/director_server.py
Labels: enhancement

#228 Split ShardDescriptor to ShardDescriptor and ShardDataset in Word Prediction Tutorial
  openfl-tutorials/interactive_api/Tensorflow_Word_Prediction/envoy/shard_descriptor.py
  openfl-tutorials/interactive_api/Tensorflow_Word_Prediction/workspace/Tensorflow_Word_Prediction.ipynb
Labels: sample

#237 Fix Market downloading
  openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/envoy/market_shard_descriptor.py
  openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/envoy/requirements.txt
  openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/PyTorch_Market_Re-ID.ipynb
  openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/requirements.txt
Labels: sample

#210 [Tutorial] Add PyTorch Histology interactive API tutorial
  openfl-tutorials/interactive_api/PyTorch_Histology/director/director_config.yaml
  openfl-tutorials/interactive_api/PyTorch_Histology/director/start_director.sh
  openfl-tutorials/interactive_api/PyTorch_Histology/director/start_director_with_tls.sh
  openfl-tutorials/interactive_api/PyTorch_Histology/envoy/.gitignore
  openfl-tutorials/interactive_api/PyTorch_Histology/envoy/envoy_config.yaml
  openfl-tutorials/interactive_api/PyTorch_Histology/envoy/histology_shard_descriptor.py
  openfl-tutorials/interactive_api/PyTorch_Histology/envoy/requirements.txt
  openfl-tutorials/interactive_api/PyTorch_Histology/envoy/start_envoy.sh
  openfl-tutorials/interactive_api/PyTorch_Histology/envoy/start_envoy_with_tls.sh
  openfl-tutorials/interactive_api/PyTorch_Histology/workspace/pytorch_histology.ipynb
  openfl-tutorials/torch_cnn_histology/histology_agg.ipynb
  openfl-tutorials/torch_cnn_histology/histology_col1.ipynb
  openfl-tutorials/torch_cnn_histology/histology_col2.ipynb
  openfl/utilities/utils.py
Labels: sample

#243 Fix envoy config in Histology tutorial
  openfl-tutorials/interactive_api/PyTorch_Histology/director/director_config.yaml
  openfl-tutorials/interactive_api/PyTorch_Histology/envoy/envoy_config.yaml
Labels: bug

#244 Set values to default and additional checks if they are unfilled
  openfl/component/director/director.py
  openfl/component/envoy/envoy.py
Labels: bug
