Repository securefederatedai/openfl, pull requests merged in 2022-03, with the labels that each got.

#338 General configuration mechanism
  openfl/component/envoy/envoy.py
  openfl/interface/director.py
  openfl/interface/envoy.py
  openfl/transport/grpc/director_client.py
  openfl/transport/grpc/director_server.py
  openfl/utilities/utils.py
  setup.py
  tests/github/interactive_api_director/experiments/pytorch_kvasir_unet/director/director_config.yaml
  tests/github/interactive_api_director/experiments/pytorch_kvasir_unet/envoy/envoy_config.yaml
  tests/github/interactive_api_director/experiments/pytorch_kvasir_unet/envoy/kvasir_shard_descriptor.py
Labels: enhancement

#349 MXNet example as a plugin to OpenFL
  openfl-tutorials/interactive_api/MXNet_landmarks/README.md
  openfl-tutorials/interactive_api/MXNet_landmarks/director/director_config.yaml
  openfl-tutorials/interactive_api/MXNet_landmarks/director/start_director.sh
  openfl-tutorials/interactive_api/MXNet_landmarks/envoy/envoy_config_one.yaml
  openfl-tutorials/interactive_api/MXNet_landmarks/envoy/envoy_config_two.yaml
  openfl-tutorials/interactive_api/MXNet_landmarks/envoy/landmark_shard_descriptor.py
  openfl-tutorials/interactive_api/MXNet_landmarks/envoy/sd_requirements.txt
  openfl-tutorials/interactive_api/MXNet_landmarks/envoy/start_envoy.sh
  openfl-tutorials/interactive_api/MXNet_landmarks/workspace/MXNet_landmarks.ipynb
  openfl-tutorials/interactive_api/MXNet_landmarks/workspace/mxnet_adapter.py
  openfl-tutorials/interactive_api/MXNet_landmarks/workspace/requirements.txt
Labels: enhancement, sample

#363 Custom task assigner unit tests.
  openfl/interface/interactive_api/experiment.py
  openfl/utilities/utils.py
  tests/openfl/component/assigner/test_custom_assigner.py
  tests/openfl/interface/interactive_api/test_experiment.py
Labels: tests

#384 Correct Kvasir Dataset links
  openfl-tutorials/Federated_PyTorch_UNET_Tutorial.ipynb
  openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy/kvasir_shard_descriptor_with_data_splitter.py
  tests/github/interactive_api_director/experiments/pytorch_kvasir_unet/data_loader.py
  tests/github/interactive_api_director/experiments/pytorch_kvasir_unet/envoy/kvasir_shard_descriptor.py
Labels: bug

#395 Build gRPC modules during develop installation
  setup.py
Labels: bug
