Repository securefederatedai/openfl, pull requests merged in 2022-01, with the labels that each got.

#283 Docs build warnings correction
  docs/conf.py
  docs/install.rst
  docs/install.singularity.rst
  docs/manual.rst
  docs/overview.rst
  docs/overview.what_is_federated_learning.rst
  docs/plan_settings.rst
  docs/running_the_federation.rst
  docs/source/openfl/components.rst
  docs/source/openfl/plugins.rst
  docs/source/utilities/pki.rst
  docs/source/utilities/splitters_data.rst
  docs/source/workflow/director_based_workflow.interactive_api.rst
  docs/source/workflow/director_based_workflow.roles.rst
  docs/source/workflow/director_based_workflow.rst
  docs/source/workflow/running_the_federation.agg_based.rst
  docs/source/workflow/running_the_federation.baremetal.rst
  docs/source/workflow/running_the_federation.certificates.rst
  docs/source/workflow/running_the_federation.docker.rst
  docs/source/workflow/running_the_federation.manual.rst
  docs/source/workflow/running_the_federation.start_nodes.rst
  docs/source/workflow/running_the_federation.tutorial.rst
Labels: documentation

#292 Bump TensorFlow to 2.7
  openfl-tutorials/Federated_FedProx_Keras_MNIST_Tutorial.ipynb
  openfl-tutorials/Federated_Keras_MNIST_Tutorial.ipynb
  openfl-tutorials/interactive_api/Tensorflow_Word_Prediction/workspace/requirements.txt
  openfl-workspace/fe_tf_adversarial_cifar/requirements.txt
  openfl-workspace/fe_torch_adversarial_cifar/requirements.txt
  openfl-workspace/keras_cnn_mnist/requirements.txt
  openfl-workspace/keras_cnn_with_compression/requirements.txt
  openfl-workspace/keras_nlp/requirements.txt
  openfl-workspace/tf_2dunet/requirements.txt
  openfl-workspace/tf_cnn_histology/requirements.txt
Labels: enhancement

#252 Basic collaborator failure handling
  openfl/component/aggregator/aggregator.py
  openfl/component/director/director.py
  openfl/component/envoy/envoy.py
  openfl/protocols/director.proto
  openfl/protocols/director_pb2.py
  openfl/protocols/director_pb2_grpc.py
  openfl/transport/grpc/director_client.py
  openfl/transport/grpc/director_server.py
Labels: enhancement

#286 Linear regression Example - custom numpy framework adapter
  openfl-tutorials/interactive_api/numpy_linear_regression/README.md
  openfl-tutorials/interactive_api/numpy_linear_regression/director/director_config.yaml
  openfl-tutorials/interactive_api/numpy_linear_regression/envoy/envoy_config.yaml
  openfl-tutorials/interactive_api/numpy_linear_regression/envoy/linreg_shard_descriptor.py
  openfl-tutorials/interactive_api/numpy_linear_regression/envoy/requirements.txt
  openfl-tutorials/interactive_api/numpy_linear_regression/workspace/LinReg.ipynb
  openfl-tutorials/interactive_api/numpy_linear_regression/workspace/SingleNotebook.ipynb
  openfl-tutorials/interactive_api/numpy_linear_regression/workspace/custom_adapter.py
  openfl-tutorials/interactive_api/numpy_linear_regression/workspace/requirements.txt
  openfl-tutorials/interactive_api/numpy_linear_regression/workspace/start_federation.ipynb
  openfl/component/envoy/envoy.py
  openfl/interface/interactive_api/experiment.py
Labels: sample

#297 Add dispatching by system and architecture while downloading step CLI
  openfl/component/ca/ca.py
Labels: enhancement

#288 Default random seed for non-deterministic DataSplitters
  openfl/utilities/data_splitters/numpy.py
  tests/openfl/utilities/test_data_splitters.py
  tests/openfl/utilities/test_path_check.py
Labels: bug

#279 Fixes delta updates = True
  openfl-workspace/workspace/plan/defaults/aggregator.yaml
  openfl/component/aggregator/aggregator.py
Labels: bug
