Repository securefederatedai/openfl, pull requests merged in 2022-02, with the labels that each got.

#304 Add "INSTALL_SOURCES" flag to base Dockerfile
  openfl-docker/Dockerfile.base
Labels: enhancement

#307 Migrate to jupyter lab
  docs/source/workflow/running_the_federation.notebook.rst
  docs/source/workflow/running_the_federation.tutorial.rst
  openfl-tutorials/interactive_api/PyTorch_DogsCats_ViT/README.md
  openfl-tutorials/interactive_api/PyTorch_Lightning_MNIST_GAN/README.md
  openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/README.md
  openfl-tutorials/interactive_api/Tensorflow_MNIST/README.md
  openfl-tutorials/interactive_api/Tensorflow_Word_Prediction/README.md
  openfl/interface/tutorial.py
  setup.py
Labels: enhancement

#305 Added scheduler support
  openfl-tutorials/interactive_api/PyTorch_DogsCats_ViT/workspace/PyTorch_DogsCats_ViT.ipynb
  openfl/federated/task/task_runner.py
  openfl/interface/interactive_api/experiment.py
  openfl/plugins/frameworks_adapters/pytorch_adapter.py
Labels: enhancement

#309 Fix hadolint issues in base Dockerfile
  openfl-docker/Dockerfile.base
Labels: bug

#308 Add adaptive federated optimization
  docs/overriding_agg_fn.rst
  openfl-tutorials/interactive_api/Tensorflow_MNIST/workspace/Tensorflow_MNIST.ipynb
  openfl/component/aggregation_functions/__init__.py
  openfl/component/aggregation_functions/adagrad_adaptive_aggregation.py
  openfl/component/aggregation_functions/adam_adaptive_aggregation.py
  openfl/component/aggregation_functions/core/__init__.py
  openfl/component/aggregation_functions/core/adaptive_aggregation.py
  openfl/component/aggregation_functions/core/interface.py
  openfl/component/aggregation_functions/geometric_median.py
  openfl/component/aggregation_functions/median.py
  openfl/component/aggregation_functions/weighted_average.py
  openfl/component/aggregation_functions/yogi_adaptive_aggregation.py
  openfl/utilities/optimizers/__init__.py
  openfl/utilities/optimizers/numpy/__init__.py
  openfl/utilities/optimizers/numpy/adagrad_optimizer.py
  openfl/utilities/optimizers/numpy/adam_optimizer.py
  openfl/utilities/optimizers/numpy/base_optimizer.py
  openfl/utilities/optimizers/numpy/yogi_optimizer.py
  setup.py
  tests/openfl/utilities/optimizers/__init__.py
  tests/openfl/utilities/optimizers/func_for_optimization.py
  tests/openfl/utilities/optimizers/test_numpy_optimizers.py
Labels: enhancement, aggregation algo

#340 Hugging face transformers tutorial for audio classification using SUPERB dataset
  openfl-tutorials/interactive_api/PyTorch_Huggingface_transformers_SUPERB/README.md
  openfl-tutorials/interactive_api/PyTorch_Huggingface_transformers_SUPERB/director/director_config.yaml
  openfl-tutorials/interactive_api/PyTorch_Huggingface_transformers_SUPERB/director/start_director.sh
  openfl-tutorials/interactive_api/PyTorch_Huggingface_transformers_SUPERB/envoy/envoy_config.yaml
  openfl-tutorials/interactive_api/PyTorch_Huggingface_transformers_SUPERB/envoy/sd_requirements.txt
  openfl-tutorials/interactive_api/PyTorch_Huggingface_transformers_SUPERB/envoy/start_envoy.sh
  openfl-tutorials/interactive_api/PyTorch_Huggingface_transformers_SUPERB/envoy/superb_shard_descriptor.py
  openfl-tutorials/interactive_api/PyTorch_Huggingface_transformers_SUPERB/workspace/PyTorch_Huggingface_transformers_SUPERB.ipynb
Labels: sample

#343 Task Assigner initial implementation
  docs/running_the_federation.rst
  openfl/component/aggregator/aggregator.py
  openfl/component/assigner/custom_assigner.py
  openfl/component/assigner/tasks.py
  openfl/component/collaborator/collaborator.py
  openfl/component/director/experiment.py
  openfl/federated/plan/plan.py
  openfl/interface/interactive_api/experiment.py
  openfl/protocols/aggregator.proto
  openfl/protocols/aggregator_pb2.py
  openfl/protocols/director_pb2.py
  openfl/transport/grpc/aggregator_server.py
Labels: enhancement
