Repository securefederatedai/openfl, pull requests merged in 2023-01, with the labels that each got.

#682 Fix python path in workspace context manager
  openfl/utilities/workspace.py
Labels: CritBug

#683 Fix missing NumPy int attribute
  openfl/federated/task/runner_fets_challenge.py
  openfl/federated/task/runner_pt.py
  openfl/pipelines/skc_pipeline.py
  openfl/pipelines/stc_pipeline.py
  openfl/plugins/frameworks_adapters/pytorch_adapter.py
Labels: bug

#700 Hashing function update
  openfl/experimental/utilities/metaflow_utils.py
Labels: workflow_interface

#707 Add tests for EDEN Compression Pipeline
  .github/workflows/taskrunner_eden_pipeline.yml
  openfl-workspace/torch_cnn_mnist_eden_compression/.workspace
  openfl-workspace/torch_cnn_mnist_eden_compression/plan/cols.yaml
  openfl-workspace/torch_cnn_mnist_eden_compression/plan/data.yaml
  openfl-workspace/torch_cnn_mnist_eden_compression/plan/defaults
  openfl-workspace/torch_cnn_mnist_eden_compression/plan/plan.yaml
  openfl-workspace/torch_cnn_mnist_eden_compression/requirements.txt
  openfl-workspace/torch_cnn_mnist_eden_compression/src/__init__.py
  openfl-workspace/torch_cnn_mnist_eden_compression/src/mnist_utils.py
  openfl-workspace/torch_cnn_mnist_eden_compression/src/pt_cnn.py
  openfl-workspace/torch_cnn_mnist_eden_compression/src/ptmnist_inmemory.py
Labels: eden_compression
